### ISSUE TITLE
Enable auto-dependency updates to keep the federation example current

### ISSUE THREAD

**Issue by setchy** [Netflix/dgs-federation-example#11]
Add dependabot or renovate to this example repo to keep it up to date as the underlying dgs-framework evolves

**Comment by setchy** [comment]
@berngp - was going back through all my open GH Issues and noticed you have 👍 this one.

Is this something you have access to enable?

**Comment by berngp** [comment]
Yes, will do.

**Comment by berngp** [comment]
Sorry for the delay @setchy, address in #13.
