### ISSUE TITLE
Using federation jvm for apollo gateway

### ISSUE THREAD

**Issue by JonathanGladwin** [Netflix/dgs-federation-example#6]
Hi,

I want to use GraphQL demo of using the DGS framework together but with "Apollo Federation JVM" (below url) as gateway in place of node apollo-gateway. How is this possible and is there any sample for combining this together?
https://github.com/apollographql/federation-jvm/tree/v0.6.3

Thanks.

**Comment by paulbakker** [comment]
@JonathanGladwin The Apollo Federation JVM is a library, not a gateway. If you would go implement your own gateway, you would likely use this library, but it's only part of the story.
The library is also used inside the DGS Framework to make a dgs federation compatible.
